=== Mendo-005/DAM2/AADD/A1/ra1-practica-evaluable-Mendo-005-main/ra1-practica-evaluable-Mendo-005-main/src/test/resources/hospital_2526.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento raíz -->
  <xs:element name="Hospital">
    <xs:complexType>
      <xs:sequence>
		<xs:element name="nombre" type="xs:string"/>
		<xs:element name="ciudad" type="xs:string"/>
        <xs:element ref="Medico" maxOccurs="unbounded"/>
        <xs:element ref="Paciente" maxOccurs="unbounded"/>
        <xs:element ref="Citas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Médicos -->

        <xs:element name="Medico">
          <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="especialidad" type="xs:string" use="required"/>
			<xs:attribute name="Nombre" type="xs:string" use="required"/>
			<xs:attribute name="Apellido" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
   

  <!-- Pacientes -->
 
        <xs:element name="Paciente">
          <xs:complexType>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="seguro" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Si"/>
                  <xs:enumeration value="No"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
			<xs:attribute name="Nombre" type="xs:string" use="required"/>
			<xs:attribute name="Apellido" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
   

  <!-- Citas -->
  <xs:element name="Citas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Cita" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="PacienteRef">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:IDREF" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="MedicoRef">
                <xs:complexType>
                  <xs:attribute name="id" type="xs:IDREF" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="Motivo" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
            <xs:attribute name="fecha" type="xs:date" use="required"/>
            <xs:attribute name="estado" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="Confirmada"/>
                  <xs:enumeration value="Pendiente"/>
                  <xs:enumeration value="Cancelada"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Mendo-005/DAM2/AADD/A1/ra1-practica-evaluable-Mendo-005-main/ra1-practica-evaluable-Mendo-005-main/src/test/resources/hospital_Zaragoza_jose_sala.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hospital_2526.xsd">
    <nombre>Hospital General Central</nombre>
    <ciudad>Zaragoza</ciudad>
    <Medico Apellido="Sanz Diaz" Nombre="Luisa" especialidad="Nefrologia" id="M04"/>
    <Medico Apellido="Perez Lopez" Nombre="Juan" especialidad="Neurologia" id="M03"/>
    <Medico Apellido="Pin Delgado" Nombre="Pedro" especialidad="Traumatologia" id="M05"/>
    <Medico Apellido="Martinez Ruiz" Nombre="Carlos" especialidad="Pediatria" id="M002"/>
    <Medico Apellido="Perez Gomez" Nombre="Laura" especialidad="Cardiologia" id="M001"/>
    <Paciente Apellido="Lopez Sanchez" Nombre="Maria" id="P100" seguro="Si"/>
    <Paciente Apellido="Garcia Torres" Nombre="Javier" id="P101" seguro="No"/>
    <Citas>
        <Cita estado="Confirmada" fecha="2025-10-05" id="C001">
            <PacienteRef id="P100"/>
            <MedicoRef id="M001"/>
            <Motivo>Chequeo cardiologico anual</Motivo>
        </Cita>
        <Cita estado="Pendiente" fecha="2025-10-07" id="C002">
            <PacienteRef id="P101"/>
            <MedicoRef id="M002"/>
            <Motivo>Revision pediatrica</Motivo>
        </Cita>
    </Citas>
</Hospital>
